SELECT T2.LOAN_SEQ_NUM_TEXT as LOAN_SEQ_NUM ,T2.CREDIT_SCORE ,T2.FIRST_PAYMENT
,T2.FIRST_TIME_HOMEBUYER_FLAG ,T2.MATURITY_DATE ,T2.MSA_CODE ,T2.MI_PERT
,T2.NUM_UNITS ,T2.OCCC_STATUS ,T2.ORIG_CLTV ,T2.ORIG_DTI_RATIO ,T2.ORIG_UPB
,T2.ORIG_LTV ,T2.ORIG_INTEREST_RATE ,T2.CHANNEL ,T2.PPM_FLAG
,T2.AMORTIZATION_TYPE_TEXT as AMORTIZATION_TYPE ,T2.PROPERTY_STATE_TEXT as
PROPERTY_STATE ,T2.PROPERTY_TYPE_TEXT as PROPERTY_TYPE ,T2.POSTAL_CODE
,T2.LOAN_PURPOSE ,T2.ORIG_LOAN_TERM ,T2.NUM_BORROWERS ,T2.SELLER_NAME_TEXT as
SELLER_NAME ,T2.SERVICER_NAME_TEXT as SERVICER_NAME ,T2.SUPER_CONFORMING_FLAG
,T2.PREHARP_LOAN_SEQ_NUM_TEXT as PREHARP_LOAN_SEQ_NUM ,T2.PROGRAM_INDICATOR
,T2.HARP_INDICATOR ,T2.PROPERTY_VALUATION_METHOD ,T2.INTEREST_ONLY_INDICATOR ,
T1.MONTHLY_REPORTING_PERIOD ,T1.CURRENT_ACTUAL_UPB ,T1.CURRENT_LOAN_DLQCY_STATUS
,T1.LOAN_AGE ,T1.REM_MONTHS_LEGAL_MATURITY ,T1.DEFECT_SETTLEMENT_DATE
,T1.MODIFICATION_FLAG ,T1.ZERO_BALANCE_CODE ,T1.ZERO_BALANCE_EFFECTIVE_DATE
,T1.CURRENT_INTEREST_RATE ,T1.CURRENT_DEFERRED_UPD ,T1.DDLPI ,T1.MI_RECOVERIES
FROM ZDWxx_FMACTB_PERF1 T1 INNER JOIN ZDWxx_FMACTB_LOAN_ORIG1_VSAM T2
ON T1.LOAN_SEQ_NUM = T2.LOAN_SEQ_NUM_TEXT